src/cliAgent.ts
src/controllers/did/DidController.ts

- Integrate the Indicio platform with the Indy Ledger.
- Additionally, the PR aims to set Bcovrin as the default Indy Ledger for the system.
- Configurations and settings will be updated to enable the use of Bcovrin as the default Indy Ledger, ensuring that it is automatically selected when the system starts up.
- Indicio is a decentralized identity platform that leverages blockchain technology to provide secure and privacy-focused identity solutions.
- Setting Bcovrin as the default ledger will streamline the user experience, reducing the need for manual configuration and ensuring a seamless setup for new users.

 Integrating Indicio Ledger, and Starting Bcovrin by Default

---

src/controllers/did/DidController.ts
src/controllers/multi-tenancy/MultiTenancyController.ts
src/controllers/types.ts
src/routes/routes.ts

Added legacy connection API and also add the get invitation by invitatioId

---

src/controllers/agent/AgentController.ts

1.GET Api Check if the Agent is currently running or not

Get agent status if running or not

---

src/controllers/multi-tenancy/MultiTenancyController.ts
src/routes/routes.ts

1. GET API: Connection details by connectionId and TenantId for multi-tenant

feat: Connection information for multi-tenants by connection ID

---

patches/@aries-framework+anoncreds+0.4.0.patch
src/controllers/credentials/CredentialController.ts
src/controllers/multi-tenancy/MultiTenancyController.ts
src/controllers/proofs/ProofController.ts
src/routes/routes.ts

1. Out Of Band for Issuance and Verification support
2. Multi-Tenant agent Out Of Band for Issuance and Verification support

feat: Out-Of-Band in Issuance and Verification functionality

---

Dockerfile

1. Added the command for the patch aries-framework/annoncreds in dockerfile

fix: Added the command for the patch aries-framework/annoncreds

---

src/cli.ts
src/cliAgent.ts
src/controllers/agent/AgentController.ts
src/controllers/credentials/CredentialDefinitionController.ts
src/controllers/credentials/SchemaController.ts
src/controllers/did/DidController.ts
src/controllers/endorser-transaction/EndorserTransactionController.ts
src/controllers/multi-tenancy/MultiTenancyController.ts
src/controllers/types.ts

1. Support indicio testnet, demonet network

feat: Support indicio demonet network

---

src/controllers/credentials/CredentialDefinitionController.ts
src/controllers/credentials/SchemaController.ts
src/controllers/endorser-transaction/EndorserTransactionController.ts
src/controllers/multi-tenancy/MultiTenancyController.ts
src/enums/enum.ts

1. Solved the bug for get cred-def and schema and endorsement also

fix: Get cred-def and schema with unqualified DID  

---

src/controllers/credentials/CredentialDefinitionController.ts
src/controllers/credentials/SchemaController.ts
src/controllers/endorser-transaction/EndorserTransactionController.ts
src/controllers/multi-tenancy/MultiTenancyController.ts
src/enums/enum.ts

1. Solved the enum issue for export in the schema and credential-def service

fix: solved the enum issue in schema and credDef

---

src/cliAgent.ts

Added the author agreement wallet version for the `indicio:mainnet` network.
This change is necessary to incorporate the version of the author agreement wallet into the mainnet environment, ensuring compatibility and compliance with the required standards.
Modified in cliAgent.ts to integrate the updated wallet version. Tested the changes thoroughly to ensure proper functioning in the `indicio:mainnet` network.

feat: Added the author agreement wallet version for indicio:mainnet

---

.gitignore
src/controllers/multi-tenancy/MultiTenancyController.ts
src/controllers/types.ts

- Generate a DID Document with the key type of bls12381g2 or ed25519 for a specific domain using the did:web method

feat: did:web didDocument creation

---

src/cli.ts
src/cliAgent.ts
src/controllers/multi-tenancy/MultiTenancyController.ts

- Implemented the withTenantAgent function to streamline and enhance session management, providing a more efficient and modular solution.
- The introduction of withTenantAgent aims to improve code readability by encapsulating session management logic within a dedicated function.
- Added the withTenantAgent function to encapsulate session management operations.
- Updated relevant parts of the codebase to utilize the new function for improved session handling.
- Conducted thorough testing to ensure the reliability and correctness of the changes.

 refactor: implemented the withTenantAgent function to enhance session management.

---

src/events/ProofEvents.ts
src/routes/routes.ts
src/routes/swagger.json

1. Included the format data within the proof's webhook

feat: Included the format data within the proof's webhook 

---

package.json
yarn.lock

- remove `ref-napi` from dependencies and add in `resolutions`  from

fix: ref napi issue

---

patches/@credo-ts+core+0.5.3+002+fix-process-problem-report.patch

- Added a patch to fix problem report processing

fix: process problem report

---

package.json
samples/cliConfig.json
src/cliAgent.ts
yarn.lock

- Updated contract address and packages

refactor: updated contract address and packages

---

samples/cliConfig.json
src/cli.ts
src/cliAgent.ts
src/controllers/did/DidController.ts
src/controllers/multi-tenancy/MultiTenancyController.ts
src/controllers/polygon/PolygonController.ts
src/controllers/types.ts
src/routes/routes.ts
src/routes/swagger.json
src/server.ts
src/utils/ServerConfig.ts

- Added schema URL in W3C schema response

feat: Added schema URL in W3C schema response

---

package.json
samples/cliConfig.json
src/cliAgent.ts
yarn.lock

- Updated contract address and package

chore: updated contract address and packages for major package release

---

src/cliAgent.ts

Change TAA version for indicio testnet
Fix issues with writing from indicio testnet to ledger

fix: TAA versioning for indicio testnet

---

src/controllers/multi-tenancy/MultiTenancyController.ts
src/controllers/polygon/PolygonController.ts
src/routes/swagger.json

- Error handling for insufficient balance

refactor: error handling for insufficient balance

---

Dockerfile

- updated docker file
- To apply patches for installing new packages

fix: updated docker file

---

src/controllers/proofs/ProofController.ts

- Error handling for Proof Controller

refactor: error handling for proof controller

---

src/controllers/polygon/PolygonController.ts

- Improved error handling of polygon controller.

refactor: error handling for polygon controller

---

src/controllers/endorser-transaction/EndorserTransactionController.ts
src/controllers/types.ts

- Improved error handling of endorser controller.

refactor: error handling for endorser controller

---

samples/cliConfig.json

- Updated schema URL for `fileServerUrl`

fix: schema file server URL

---

src/events/ReuseConnectionEvents.ts
src/server.ts

- Created new event for reuse connection

feat: created new event for reuse connection

---

taskdef/credo-fargate-taskdef.json

Changes in taskdef.json file for fargate

Fix: taskdef file changes

---

src/events/CredentialEvents.ts
src/events/ProofEvents.ts
src/routes/routes.ts
src/routes/swagger.json

- Added formatData in credential webhook
- Added webhook for dedicated agent

feat: add formatData in credential webhook

---

patches/@credo-ts+core+0.5.3+003+credential-record-debug-patch.patch

- Added credential record patch

fix: add credential record patch

---

patches/@credo-ts+core+0.5.3+004+added-prettyVc-in-JsonCredential-interface.patch
src/server.ts

- Added PrettyVc patch
- Passing HTML certificate while creating offer

fix: add prettyVc patch

---

src/controllers/did/DidController.ts
src/controllers/multi-tenancy/MultiTenancyController.ts

- Added assertion method in did web

fix: added assertion method in did web

---

src/events/ReuseConnectionEvents.ts

- Added reuse connection event

fix:added-reuse-connection-event

---

patches/@credo-ts+core+0.5.3+005+commenting validationPresentation to avoid abandoned issue.patch

- Commenting validatePresentation()  due to intermittent abandoned issue

fix: added patch for avoiding  proof abandoned issue

---

patches/@credo-ts+tenants+0.5.3+001+cache-tenant-record-patch.patch

- Added cache tenant record patch

fix:added cache tenant record patch

---

.github/ISSUE_TEMPLATE/DMP_2024.yml
LICENSE

- Update occurrences of `Blockster Labs` to `Ayanworks`

chore: transition from Blockster Labs to Ayanworks

---

src/controllers/credentials/CredentialController.ts
src/controllers/multi-tenancy/MultiTenancyController.ts

- Implemented credential attribute details

feat:implemented form data for credentials

---

package.json

- updated polygon-module package version

bump: updated polygon-module package version

---

package.json
src/controllers/credentials/CredentialController.ts
src/controllers/multi-tenancy/MultiTenancyController.ts

Sync changes from DEV to QA

---

package.json

bump up version for release

---

src/controllers/multi-tenancy/MultiTenancyController.ts

- Corrected the polygon routes

fix: changed the polygon routes

---

package.json
src/controllers/credentials/CredentialController.ts
src/controllers/did/DidController.ts
src/controllers/multi-tenancy/MultiTenancyController.ts
src/controllers/proofs/ProofController.ts
src/controllers/types.ts
src/events/CredentialEvents.ts
src/events/ProofEvents.ts

####What
- Added `threadId` in credential controller
- Changed keytype option for polygon
- Changed the polygon schema route
- Webhook changes for `Credential` and `Proof`

merge: develop to qa

---

src/controllers/proofs/ProofController.ts

-Added ProofRecordThId in create offer oob  for proof in dedicated agent

fix: add proof record thread id in dedicated agent for creating proof request oob

---

src/controllers/proofs/ProofController.ts

- Added proof record thread id in dedicated agent for creating oob proof request

fix:add proof record thread id

---

src/controllers/multi-tenancy/MultiTenancyController.ts
src/controllers/proofs/ProofController.ts

- Sync changes from DEV to QA.

Sync changes from DEV to QA.

---

compass.yml

fix: added compass.yml file

---

compass.yml

- fix: resolved prettier errors for compass.yml file

fix: resolved prettier errors for compass.yml file

---

package.json
yarn.lock

chore: remove unwanted package

chore: remove unwanted package

---

package.json
yarn.lock

- Sync up changes from DEV to Qa.

Merge: Sync up changes from DEV to QA (29/07/2025)

---

src/controllers/multi-tenancy/MultiTenancyController.ts

chore: fix imports

---

src/tracer.ts

refactor: changed env endpoints

---

scripts/taskdef/credo-ecs-taskdef.json

feat: update taskef for ARM arch

---

.github/workflows/continuous-delivery.yml
Dockerfile

- Updated the workflow file to build and push multi-architecture Docker images.
- Added a network-timeout configuration in the Dockerfile to improve dependency installation when running under QEMU.

feat: multi-arch-packages

---

.github/dco.yml

feat: add remediation support

---

src/controllers/agent/AgentController.ts

- DCO issue through remediation

fix: DCO issue through remediation
